# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    git config gitgitgadget.CIsmtpUser '$(gitgitgadget.CIsmtpUser)'
    git config gitgitgadget.CIsmtpHost '$(gitgitgadget.CIsmtpHost)'
    git config gitgitgadget.CIsmtpPass '$(gitgitgadget.CIsmtpPass)'
    git config gitgitgadget.CIsmtpOpts '$(gitgitgadget.CIsmtpOpts)'
    git config gitgitgadget.CIimapHost '$(gitgitgadget.CIimapHost)'
  displayName: 'Configure ethereal SMTP'
  condition: ne(variables['gitgitgadget.CIsmtpPass'], '')

- script: |
    npm install
    npm run build
    npm run ci
  displayName: 'npm install, build and test'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFiles: 'junit.xml'
  condition: succeededOrFailed()
